on: [push]

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    name: Tag Path Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ github.ref_name }}
      - uses: online-concept-aps/PathTagBump@v0.0.3 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prefix-tag: 'customer'
#      - name: show tag what
#        run: echo "the new tag is ${{ steps.pathtagbump.outputs.new-tag  }}"